//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pkRevitRibbon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AssemblyNeedLoading {
            get {
                return ((bool)(this["AssemblyNeedLoading"]));
            }
            set {
                this["AssemblyNeedLoading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DevelopmentPathRoot {
            get {
                return ((string)(this["DevelopmentPathRoot"]));
            }
            set {
                this["DevelopmentPathRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MakeTheNextOneDevelopment {
            get {
                return ((bool)(this["MakeTheNextOneDevelopment"]));
            }
            set {
                this["MakeTheNextOneDevelopment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevitDatasheets_DevLocation_DataSheets {
            get {
                return ((string)(this["pkRevitDatasheets_DevLocation_DataSheets"]));
            }
            set {
                this["pkRevitDatasheets_DevLocation_DataSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevitDatasheetsLoadName {
            get {
                return ((string)(this["pkRevitDatasheetsLoadName"]));
            }
            set {
                this["pkRevitDatasheetsLoadName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_DevLocation_Misc {
            get {
                return ((string)(this["pkRevit_DevLocation_Misc"]));
            }
            set {
                this["pkRevit_DevLocation_Misc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_LoadName_Misc {
            get {
                return ((string)(this["pkRevit_LoadName_Misc"]));
            }
            set {
                this["pkRevit_LoadName_Misc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_LoadName_ScheduleEdit {
            get {
                return ((string)(this["pkRevit_LoadName_ScheduleEdit"]));
            }
            set {
                this["pkRevit_LoadName_ScheduleEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_DevLocation_ScheduleEdit {
            get {
                return ((string)(this["pkRevit_DevLocation_ScheduleEdit"]));
            }
            set {
                this["pkRevit_DevLocation_ScheduleEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_LoadName_TransformSliders {
            get {
                return ((string)(this["pkRevit_LoadName_TransformSliders"]));
            }
            set {
                this["pkRevit_LoadName_TransformSliders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_DevLocation_TransformSliders {
            get {
                return ((string)(this["pkRevit_DevLocation_TransformSliders"]));
            }
            set {
                this["pkRevit_DevLocation_TransformSliders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_LoadName_CircleOutFamilies {
            get {
                return ((string)(this["pkRevit_LoadName_CircleOutFamilies"]));
            }
            set {
                this["pkRevit_LoadName_CircleOutFamilies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_DevLocation_CircleOutFamilies {
            get {
                return ((string)(this["pkRevit_DevLocation_CircleOutFamilies"]));
            }
            set {
                this["pkRevit_DevLocation_CircleOutFamilies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_LoadName_LoadingPlacing_Families {
            get {
                return ((string)(this["pkRevit_LoadName_LoadingPlacing_Families"]));
            }
            set {
                this["pkRevit_LoadName_LoadingPlacing_Families"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_DevLocation_LoadingPlacing_Families {
            get {
                return ((string)(this["pkRevit_DevLocation_LoadingPlacing_Families"]));
            }
            set {
                this["pkRevit_DevLocation_LoadingPlacing_Families"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_LoadName_ViewportManagement {
            get {
                return ((string)(this["pkRevit_LoadName_ViewportManagement"]));
            }
            set {
                this["pkRevit_LoadName_ViewportManagement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pkRevit_DevLocation_ViewportManagement {
            get {
                return ((string)(this["pkRevit_DevLocation_ViewportManagement"]));
            }
            set {
                this["pkRevit_DevLocation_ViewportManagement"] = value;
            }
        }
    }
}
